encoder:
  model_name: "dinov2_vitg14_reg"
  num_trainable_blocks: 6
  return_classtok: true
decoder:
  dec_embed_dim: 1536  # Увеличено для ViT-G
  dec_num_heads: 16
  dec_depth: 12
  mlp_ratio: 4
masking:
  mask_ratio: 0.9
  patch_size: 14
augmentation:
  img_res: 322
train:
  classtoken: true
  random: false
globaldesc:
  dim: 512
eval:
  refinetopcands: 200
  memoryeffmode: false
  sequence_window: 3  # Размер окна для последовательности
  use_both_cams: true  # Использовать обе камеры
dataset_locations:
  itlp: "itlp_dataset"  # Фиктивный путь, будет переопределен